yolo:
  type: "yolov4"
  iou_threshold: 0.5
  score_threshold: 0.4
  max_boxes: 100
  num_classes: 3
  strides: "32,16,8"
  anchors: "12,16 19,36 40,28 36,75 76,55 72,146 142,110 192,243 459,401"
  mask: "6,7,8 3,4,5 0,1,2"
  name_path: "./data/coco/AMIR.name"

train:
  label: "coco_yolov4"
  anno_path: "./data/coco/anno1.txt"
  image_size: "320,352,384,416,448,480,512,544,576,608"

  batch_size: 4
  init_weight_path: "./ckpts/yolov4_weights.h5"
  save_weight_path: "./ckpts"

  loss_type: "CIoU+FL"

  mosaic: False
  label_smoothing: True
  normal_method: True

  ignore_threshold: 0.5

test:
  anno_path: "./data/coco/anno2.txt"
  image_size: "320,352,384,416,448,480,512,544,576,608"
  batch_size: 1
  init_weight_path: "./ckpts/yolov4_weights.h5"
  