yolo:
  type: "yolov4"
  iou_threshold: 0.213
  score_threshold: 0.4
  max_boxes: 100
  num_classes: 7
  strides: "32,16,8"
  anchors: "12,16 19,36 40,28 36,75 76,55 72,146 142,110 192,243 459,401"
  mask: "6,7,8 3,4,5 0,1,2"
  name_path: "./data/coco/YOLOv4_3_7Classes.name"

train:
  label: "coco_yolov4"
  anno_path: "./data/coco/anno3.txt"
  image_size: "416"

  batch_size: 64
  init_weight_path: "./ckpts/yolov4_weights.h5"
  save_weight_path: "./ckpts"

  loss_type: "CIoU+FL"

  mosaic: False
  label_smoothing: True
  normal_method: True

  ignore_threshold: 0.5

test:
  anno_path: "./data/coco/anno4.txt"
  image_size: "416"
  batch_size: 1
  init_weight_path: "./ckpts/yolov4_weights.h5"
  